import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Envision tools",
  description: "Generated by Hulesh Jangde",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.className}  w-screen h-full px-10 py-2 overflow-x-hidden  dark:bg-black bg-white  dark:bg-dot-white/[0.2] bg-dot-black/[0.2] relative flex items-center justify-center`}
      >
        <div>
          <Navbar />
          <div className="mt-10">{children}</div>
          <Footer />
        </div>
      </body>
    </html>
  );
}
