export const artPrompts: string[] = [
  "An ornate, baroque-inspired peacock with elaborate, swirling feathers.",
  "A vibrant cityscape at twilight, with towering skyscrapers and neon lights reflecting on rain-soaked streets.",
  "Create a digital collage that blends the aesthetics of cyberpunk and Art Deco.",
  "An underwater steampunk laboratory where mermaids study ancient artifacts.",
  "A neon-lit cyberpunk cityscape with rain-soaked streets and holographic billboards.",
  "Design a whimsical, fantastical forest filled with talking animals and enchanted trees.",
  "An abstract representation of the feeling of nostalgia with a warm, sepia-toned palette.",
  "An ethereal underwater scene with shimmering coral reefs, graceful sea turtles, and schools of bioluminescent creatures.",
  "An eerie, abandoned carnival at twilight, shrouded in mist and mystery.",
  "A whimsical forest filled with talking animals, hidden doorways, and trees that come to life at night.",
  "An abstract portrait capturing the essence of joy through bold brushstrokes and vibrant splashes of color.",
  "A surreal still life featuring a floating teacup, melting clocks, and a bouquet of flowers transitioning into butterflies.",
  "A whimsical interpretation of a bustling farmers' market, with exaggerated colors and shapes.",
  "An impressionist city park scene on a sunny day with dappled shade and children playing.",
  "Craft an abstract expressionist piece conveying a sense of frenzied energy and motion.",
  "A romantic Art Nouveau-style poster for a vintage circus with a graceful acrobat.",
  "Design a post-apocalyptic wasteland with rusted machinery and a blood-red sky.",
  "A dreamlike landscape where fluffy clouds take the form of mythical creatures and cotton candy rivers flow through candy cane mountains.",
  "A minimalist, monochromatic landscape featuring a lone tree on a snowy hill.",
  "A Gothic cathedral bathed in eerie moonlight, with intricate stained glass windows.",
  "Create a surreal dreamscape where gravity seems to have lost its rules.",
  "A mosaic of geometric patterns and bold colors that evoke a sense of jubilation.",
  "A melancholic portrait of an aging astronaut gazing at Earth from space.",
  "A futuristic cityscape with flying cars, holographic billboards, and towering skyscrapers stretching into the clouds.",
  "A futuristic cityscape inspired by the architecture of the ancient Mayans.",
  "Craft a digital painting that combines elements of Norse mythology with futuristic technology.",
  "A post-impressionist interpretation of a sunny Provencal vineyard.",
  "An abstract portrait suggesting the complexity of human emotions.",
  "A minimalist composition depicting the tranquility of a Zen garden, with carefully arranged rocks and ripples in a calm pond.",
  "Create a vibrant cityscape in the style of Vincent van Gogh, with swirling stars overhead.",
  "An otherworldly alien cityscape, reminiscent of H.R. Giger's biomechanical aesthetic.",
  "Paint a still life of antique pocket watches in a steampunk style.",
  "A cosmic journey through a wormhole, replete with swirling colors and shapes.",
  "Design a digital graffiti mural that captures the spirit of rebellion.",
  "A whimsical, steampunk-style airship soaring above a Victorian-inspired city.",
  "A contemporary reinterpretation of the Mona Lisa in a pop art style.",
  "A pointillism-inspired artwork capturing the energy and vibrancy of a bustling marketplace, filled with people, fruits, and colorful textiles.",
  "A serene Japanese garden with cherry blossoms in full bloom and a koi pond.",
  "A post-apocalyptic wasteland with a lone, weathered mailbox as the focal point.",
  "A chaotic, abstract representation of a thunderstorm in motion.",
  "An impressionistic seascape showcasing the dramatic interplay of light and shadow on crashing waves and a rocky coastline.",
  "An abstract landscape that conveys the concept of infinity and boundlessness.",
  "A surrealist self-portrait exploring the idea of self-identity and transformation.",
  "Create a cybernetic creature that blurs the line between man and machine.",
  "A surreal desert landscape with floating islands, upside-down cacti, and a sky filled with swirling galaxies.",
  "An ethereal forest scene with luminescent mushrooms and misty blue foliage.",
  "An ethereal underwater palace with mermaid inhabitants and shimmering coral chandeliers.",
  "An expressionist interpretation of the chaos and vibrancy of a carnival.",
  "A surreal, dreamlike forest with mythical creatures and floating islands.",
  "A minimalist, monochromatic study of light and shadow in an urban environment.",
];
